#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'supervisord-syslog-notifier==0.0.1','console_scripts','supervisord_syslog_notifier'
__requires__ = 'supervisord-syslog-notifier==0.0.1'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('supervisord-syslog-notifier==0.0.1', 'console_scripts', 'supervisord_syslog_notifier')()
    )